version: '3.9'
services:
    adguard:
        image: adguard/adguardhome
        ports:
            - '5443:5443/udp'
            - '5443:5443/tcp'
            - '8853:8853/udp'
            - '853:853/udp'
            - '784:784/udp'
            - '853:853/tcp'
            - '3000:3000/tcp'
            - '443:443/udp'
            - '443:443/tcp'
            - '80:80/tcp'
            - '53:53/udp'
            - '53:53/tcp'
        volumes:
            - '/apps/adguard/conf:/opt/adguardhome/conf'
            - '/apps/adguard/work:/opt/adguardhome/work'
        restart: unless-stopped
        container_name: adguardhome